"""
patch_intelligence.py
Upgrades the Potential Clients tab to load live data from
data/intelligence.json (generated by fetch_intelligence.py)
instead of the static POTENTIAL_CLIENTS array.
"""
import sys, re
sys.stdout.reconfigure(encoding='utf-8')

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

original_len = len(html)

# ── 1. Replace renderClients() + _renderClientCards() + POTENTIAL_CLIENTS ─────
# Find start of POTENTIAL_CLIENTS const
start = html.find('// ─── Potential Clients Tab')
if start < 0:
    start = html.find('const POTENTIAL_CLIENTS = [')
if start < 0:
    print("ERROR: cannot find POTENTIAL_CLIENTS block"); exit(1)

# Find end — after _renderClientCards closing brace
# Find the function and its closing
end_marker = 'function renderClients()'
end_idx = html.find(end_marker, start)
# Walk to end of renderClients
depth = 0; i = end_idx; started = False
while i < len(html):
    if html[i] == '{': depth += 1; started = True
    elif html[i] == '}':
        depth -= 1
        if started and depth == 0: end_clients = i + 1; break
    i += 1

# Also capture _renderClientCards
end_marker2 = 'function _renderClientCards()'
end_idx2 = html.find(end_marker2, end_clients)
depth = 0; i = end_idx2; started = False
while i < len(html):
    if html[i] == '{': depth += 1; started = True
    elif html[i] == '}':
        depth -= 1
        if started and depth == 0: end_cards = i + 1; break
    i += 1

old_block = html[start:end_cards]

NEW_CLIENTS_JS = r"""
// ─── Potential Clients Tab (Live Intelligence) ────────────────────────────────
let INTELLIGENCE_DATA = null;  // loaded from data/intelligence.json
let clientStateFilter = '', clientStageFilter = '', clientNeedFilter = '', clientSourceFilter = '';

async function loadIntelligence() {
  try {
    const r = await fetch('data/intelligence.json?t=' + Date.now());
    if (!r.ok) throw new Error('HTTP ' + r.status);
    INTELLIGENCE_DATA = await r.json();
    console.log('[Intel] Loaded', INTELLIGENCE_DATA.leads.length, 'leads');
    return true;
  } catch(e) {
    console.warn('[Intel] Could not load intelligence.json:', e.message);
    INTELLIGENCE_DATA = null;
    return false;
  }
}

function renderClients() {
  const pane = document.getElementById('tab-clients');
  if (!pane || !croData) return;

  // Always rebuild
  pane.innerHTML = '';

  // Toolbar
  const toolbar = document.createElement('div');
  toolbar.id = 'clients-toolbar';

  const sourceOpts = ['All Sources','ClinicalTrials.gov','SEC EDGAR','NIH RePORTER'];
  const stageOpts  = ['All Stages','Phase 1','Phase 2','Funding','Grant','Preclinical'];

  toolbar.innerHTML = `
    <label>Source</label>
    <select id="client-filter-source">
      ${sourceOpts.map(s=>`<option>${s}</option>`).join('')}
    </select>
    <label>Stage</label>
    <select id="client-filter-stage">
      ${stageOpts.map(s=>`<option>${s}</option>`).join('')}
    </select>
    <label>State</label>
    <select id="client-filter-state">
      <option value="">All States</option>
      ${Object.keys({MA:1,CA:1,NJ:1,NC:1,TX:1,PA:1,NY:1,MD:1,IL:1,WA:1,CO:1,FL:1,GA:1,VA:1}).map(s=>`<option>${s}</option>`).join('')}
    </select>
    <label>Need</label>
    <select id="client-filter-need">
      <option value="">All Services</option>
      ${["DMPK","ADME","Toxicology","Bioanalysis","In Vivo / Mouse Services","CMC","Protein Sciences / Biologics"].map(s=>`<option>${s}</option>`).join('')}
    </select>
    <button id="clients-refresh-btn" style="margin-left:auto;background:var(--surface2);border:1px solid var(--border);border-radius:5px;padding:4px 10px;color:var(--text-muted);font-size:11px;cursor:pointer;font-family:var(--font-body)">&#8635; Refresh</button>
    <span id="clients-count" style="font-size:10px;color:var(--text-dim);white-space:nowrap"></span>
  `;
  pane.appendChild(toolbar);

  // Metadata bar
  const metaBar = document.createElement('div');
  metaBar.id = 'clients-meta';
  metaBar.style.cssText = 'padding:4px 16px;font-size:10px;color:var(--text-dim);border-bottom:1px solid var(--border);background:var(--surface2);flex-shrink:0';
  pane.appendChild(metaBar);

  // Body
  const body = document.createElement('div');
  body.id = 'clients-body';
  pane.appendChild(body);

  // Wire filters
  ['source','stage','state','need'].forEach(f => {
    const el = document.getElementById(`client-filter-${f}`);
    if (el) el.addEventListener('change', e => {
      if (f==='source') clientSourceFilter = e.target.value === 'All Sources' ? '' : e.target.value;
      else if (f==='stage') clientStageFilter = e.target.value === 'All Stages' ? '' : e.target.value;
      else if (f==='state') clientStateFilter = e.target.value;
      else if (f==='need')  clientNeedFilter  = e.target.value;
      _renderClientCards();
    });
  });

  const refreshBtn = document.getElementById('clients-refresh-btn');
  if (refreshBtn) refreshBtn.addEventListener('click', async () => {
    refreshBtn.textContent = 'Loading...';
    INTELLIGENCE_DATA = null;
    await loadIntelligence();
    _renderClientCards();
    refreshBtn.textContent = '↺ Refresh';
  });

  // Load data then render
  if (INTELLIGENCE_DATA) {
    _renderClientCards();
  } else {
    loadIntelligence().then(() => _renderClientCards());
  }
}

function _renderClientCards() {
  const body    = document.getElementById('clients-body');
  const countEl = document.getElementById('clients-count');
  const metaEl  = document.getElementById('clients-meta');
  if (!body) return;

  // Get focal CRO for relevance sorting
  const focal = compareFocalId
    ? croData.cros.find(c => c.id === compareFocalId)
    : croData.cros.find(c => c.is_medicilon);
  const focalSvcs = new Set(focal ? (focal.services || []) : []);
  const focalName = focal ? focal.short_name : 'Medicilon';

  // Source data — combine live + static fallback
  let leads = [];
  if (INTELLIGENCE_DATA && INTELLIGENCE_DATA.leads && INTELLIGENCE_DATA.leads.length) {
    leads = INTELLIGENCE_DATA.leads;
    if (metaEl) {
      const meta = INTELLIGENCE_DATA.metadata || {};
      const gen = meta.generated ? new Date(meta.generated).toLocaleDateString('en-US',{month:'short',day:'numeric'}) : '';
      metaEl.innerHTML = `Live data: <b>${meta.total||leads.length}</b> leads &nbsp;·&nbsp; ` +
        `ClinicalTrials: <b>${meta.sources?.clinical_trials||0}</b> &nbsp;·&nbsp; ` +
        `SEC Funding: <b>${meta.sources?.sec_funding||0}</b> &nbsp;·&nbsp; ` +
        `NIH Grants: <b>${meta.sources?.nih_grants||0}</b> &nbsp;·&nbsp; ` +
        `Updated: <b>${gen}</b> &nbsp;·&nbsp; ` +
        `<span style="color:var(--gold)">Sorted by relevance to ${focalName}</span>`;
    }
  } else {
    // Fallback to static list
    leads = STATIC_CLIENTS.map(c => ({
      source: 'Curated', source_id: c.name,
      name: c.name, state: c.state, stage: c.stage,
      focus: c.focus, needs: c.needs,
      signal: c.opportunity, date: '', date_label: `Founded ${c.founded}`,
      score: 0, hub_weight: 0, url: '',
    }));
    if (metaEl) metaEl.innerHTML = '<span style="color:var(--text-dim)">Showing curated static list — run fetch_intelligence.py for live data</span>';
  }

  // Apply filters
  let filtered = leads.filter(l => {
    if (clientSourceFilter && l.source !== clientSourceFilter) return false;
    if (clientStageFilter  && l.stage  !== clientStageFilter)  return false;
    if (clientStateFilter  && l.state  !== clientStateFilter)  return false;
    if (clientNeedFilter   && !(l.needs||[]).includes(clientNeedFilter)) return false;
    return true;
  });

  // Re-score by focal CRO service overlap
  filtered.forEach(l => {
    const overlap = (l.needs||[]).filter(n => focalSvcs.has(n)).length;
    const hubW = (croData.biotech_hub_weights||{})[l.state] || l.hub_weight || 0;
    l._display_score = overlap * 15 + hubW * 4 + (l.score || 0) * 0.3;
  });
  filtered.sort((a,b) => b._display_score - a._display_score);

  if (countEl) countEl.textContent = `${filtered.length} leads`;
  body.innerHTML = '';

  if (!filtered.length) {
    body.innerHTML = '<div style="padding:30px;color:var(--text-dim);font-size:12px;text-align:center">No leads match current filters</div>';
    return;
  }

  const SOURCE_COLORS = {
    'ClinicalTrials.gov': '#3b9eff',
    'SEC EDGAR':          '#2ecc71',
    'NIH RePORTER':       '#9b59b6',
    'Curated':            '#f5a623',
  };
  const STAGE_COLORS = {
    'Phase 1':'#3b9eff','Phase 2':'#2ecc71','Phase 3':'#1abc9c',
    'Funding':'#e67e22','Grant':'#9b59b6','Preclinical':'#e74c3c',
  };

  filtered.forEach(l => {
    const overlap = (l.needs||[]).filter(n => focalSvcs.has(n));
    const missing = (l.needs||[]).filter(n => !focalSvcs.has(n));
    const matchPct = l.needs && l.needs.length
      ? Math.round(overlap.length / l.needs.length * 100) : 0;
    const stageColor  = STAGE_COLORS[l.stage]  || '#888';
    const sourceColor = SOURCE_COLORS[l.source] || '#888';
    const hubW = (croData.biotech_hub_weights||{})[l.state] || l.hub_weight || 0;

    const card = document.createElement('div');
    card.className = 'client-card';
    card.innerHTML = `
      <div class="client-card-header">
        <div class="client-stage-dot" style="background:${stageColor}" title="${l.stage}"></div>
        <div class="client-name">${l.name}</div>
        <div class="client-state-badge">${l.state}</div>
      </div>
      <div style="display:flex;gap:5px;align-items:center;margin-bottom:3px">
        <span style="font-size:9px;padding:1px 6px;border-radius:3px;background:${sourceColor}22;border:1px solid ${sourceColor}44;color:${sourceColor}">${l.source}</span>
        <span class="client-stage-label">${l.stage} · Hub ${hubW}/10 · ${l.date_label||''}</span>
      </div>
      <div class="client-focus">${(l.focus||'').slice(0,90)}</div>
      <div class="client-tags">
        ${overlap.map(n=>`<span class="client-tag need" title="Service match">✓ ${n}</span>`).join('')}
        ${missing.map(n=>`<span class="client-tag">${n}</span>`).join('')}
      </div>
      <div style="display:flex;justify-content:space-between;align-items:center;margin-top:3px">
        <div class="client-opportunity">Match ${matchPct}%${l.signal ? ' · ' + l.signal.slice(0,40) : ''}</div>
        ${l.url ? `<a href="${l.url}" target="_blank" style="font-size:9px;color:var(--accent);text-decoration:none">View →</a>` : ''}
      </div>
    `;
    card.addEventListener('click', e => {
      if (e.target.tagName === 'A') return;
      if (l.state && l.state.length === 2 && typeof openDetailPanel === 'function') {
        openDetailPanel(l.state);
      }
    });
    body.appendChild(card);
  });
}

// Static fallback (first 10 from original list)
const STATIC_CLIENTS = [
  { name:'Relay Therapeutics',     state:'MA', stage:'Phase 2', focus:'Precision oncology, protein motion', needs:['DMPK','Bioanalysis','In Vivo / Mouse Services'], founded:2016, opportunity:'High — active IND pipeline' },
  { name:'Kymera Therapeutics',    state:'MA', stage:'Phase 2', focus:'Targeted protein degradation',       needs:['DMPK','ADME','Toxicology'],                       founded:2016, opportunity:'High' },
  { name:'Absci Corporation',      state:'CA', stage:'Platform',focus:'Generative AI drug design',          needs:['Protein Sciences / Biologics','Bioanalysis'],     founded:2011, opportunity:'High' },
  { name:'Septerna',               state:'CA', stage:'Phase 1', focus:'GPCR-targeted small molecules',      needs:['DMPK','ADME','In Vivo / Mouse Services'],         founded:2022, opportunity:'High' },
  { name:'Passage Bio',            state:'PA', stage:'Phase 1', focus:'Gene therapy, rare neurological',    needs:['Toxicology','Bioanalysis','Protein Sciences / Biologics'], founded:2018, opportunity:'High' },
  { name:'Athira Pharma',          state:'WA', stage:'Phase 2', focus:'Neurodegeneration (AD)',             needs:['DMPK','Bioanalysis','In Vivo / Mouse Services'], founded:2011, opportunity:'High' },
  { name:'Tempus AI Health',       state:'IL', stage:'Commercial',focus:'AI-driven oncology diagnostics',   needs:['Biomarker / Genomics','Bioanalysis'],             founded:2015, opportunity:'High' },
  { name:'Inhibrx Biosciences',    state:'NJ', stage:'Phase 2', focus:'Rare disease biologics',            needs:['Protein Sciences / Biologics','Bioanalysis','Toxicology'], founded:2010, opportunity:'High' },
  { name:'G1 Therapeutics',        state:'NC', stage:'Commercial',focus:'Oncology supportive care',        needs:['Bioanalysis','DMPK'],                             founded:2008, opportunity:'Medium' },
  { name:'Halo Dx',                state:'TX', stage:'Phase 1', focus:'Diagnostics & oncology biomarkers', needs:['Biomarker / Genomics','Bioanalysis'],             founded:2019, opportunity:'High' },
];
"""

html = html[:start] + NEW_CLIENTS_JS + html[end_cards:]
print(f"Replaced clients block ({len(old_block):,} chars -> {len(NEW_CLIENTS_JS):,} chars)")

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f"index.html: {original_len:,} -> {len(html):,} bytes")
print("Done. Hard refresh http://localhost:8080 and click Potential Clients tab")
